name: Get Subscription Daily

on:
  schedule:
    - cron: '0 */5 * * *'  # 每五小时运行一次
  workflow_dispatch: # 允许手动触发

permissions:
  contents: write

jobs:
  execute-script:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip3 install pyYAML requests tqdm
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Collect Subscribe
        id: collect
        run: |
          python subscribe/collect.py -a -s -l 2

      - name: Create/Update Gist
        env:
          GH_TOKEN: ${{ secrets.PAT}}
        run: |
          cd data
          gh gist edit ${{ secrets.GIST_ID }} --add "proxies.yaml"
          gh gist edit ${{ secrets.GIST_ID }} --add "subscribes.txt"
          gh gist edit ${{ secrets.GIST_ID }} --add "valid-domains.txt"
